apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-root-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/dev
    repoURL: 'https://github.com/Becram/argocd-sample.git'
    targetRevision: main
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysapps-root-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/sysapps/dev
    repoURL: 'https://github.com/Becram/argocd-sample.git'
    targetRevision: main