ingress-nginx:
  controller:
    image:
      digest: ''
      pullPolicy: Always
    podAnnotations:
      linkerd.io/inject: disabled
    config:
      server-tokens: "false"
      hide-headers: "Server"
      use-forwarded-headers: "true"
    service:
      loadBalancerSourceRanges: ["0.0.0.0/0"]
      externalTrafficPolicy: "Local"
    kind: Deployment
    minReadySeconds: 5
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 5; /usr/local/openresty/nginx/sbin/nginx -c /etc/nginx/nginx.conf -s quit; while pgrep -x nginx; do sleep 1; done"]
    terminationGracePeriodSeconds: 300