apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
{{ include "deployment.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "deployment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
  {{- range .Values.containers }}
  {{- if .containerPort }}
  - protocol: {{ default "TCP" $.Values.protocol }}
    name: {{ .name }}
    port: {{ .containerPort }}
  {{- end }}
  {{- end }}
