ingress:
  enabled: true
  exposedPort: 80
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
  hosts:
  - host: app.bdhoju.com
    paths:
    - /
  tls:
  - secretName: app-1-tls
    hosts:
    - app.bdhoju.com