apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../helm_base/argocd

namespace: argocd
commonLabels:
  app.kubernetes.io/part-of: argocd-app-of-apps-example
  app.kubernetes.io/managed-by: argocd


resources:
- namespace.yml


# patchesJson6902:
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: test-helm-guestbook
#   path: patch/deployment_patch.yml
