aws-load-balancer-controller:
  fullnameOverride:
  replicaCount: 1
  clusterName: "eks-production-cluster"

  logLevel: debug
  keepTLSSecret: true
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::725061457686:role/aws-load-balancer-eksserviceaccount-role"
    name: "aws-load-balancer"