apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: sysapps/overlays/dev/argocd
    repoURL: 'https://github.com/Becram/argocd-sample.git'
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
