keycloak:
  replicaCount: 1
  ingress:
    enabled: true
    hostname: authen.bdhoju.com
    path: /
    pathType: ImplementationSpecific
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 4m
    tls: true