keycloak:
  keycloak:
    replicaCount: 1
    ingress:
      enabled: true
      path: /
      annotations: 
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 4m
  
      ## List of hosts for the ingress
      hosts:
        - authen.bdhoju.com
  
      ## TLS configuration
      tls: 
      - hosts:
          - authen.bdhoju.com
        secretName: tls-keycloak
