apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../helm_base/cert-manager

namespace: cert-manager


resources:
- namespace.yml
- cluster-issuer.yaml


# patchesJson6902:
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: test-helm-guestbook
#   path: patch/deployment_patch.yml
