# Apply secrets before applying helm chart
keycloak:
  keycloak:
    replicaCount: 2
    pdb:
      create: true
      minAvailable: 1
    postgresql:
      enabled: true
    # externalDatabase:
    #   host: data-engineering.cbfwux5trlzu.ap-southeast-1.rds.amazonaws.com
    #   user: keycloak
    #   database: bitnami-keycloak
    serviceDiscovery:
      enabled: true
    auth:
      createAdminUser: true
      adminUser: admin
      # existingSecret:
      #   name: keycloak
      #   keyMapping:
      #      admin-password: KEYCLOAK_PASSWORD
      #      management-password: WILDFLY_PASSWORD
      #      database-password: DB_PASSWORD
    proxyAddressForwarding: true
    service:
      type: ClusterIP
    rbac:
      create: true
      rules:
        - apiGroups:
            - ""
          resources:
            - pods
          verbs:
            - get
            - list