cert-manager:
  installCRDs: true
  global:
    leaderElection:
      # Override the namespace used to store the ConfigMap for leader election
      namespace: "cert-manager"
    logLevel: 6
  image:
    pullPolicy: Always
    # defaultIssuerGroup: ""
  prometheus:
    enabled: false
  webhook:
    replicaCount: 1
    image:
      pullPolicy: Always
  cainjector:
    image:
      pullPolicy: Always