cert-manager:
  installCRDs: true
  leaderElection:
    # Override the namespace used to store the ConfigMap for leader election
    namespace: "cert-manager"
  image:
    pullPolicy: Always
    # defaultIssuerGroup: ""
  prometheus:
    enabled: false
  webhook:
    replicaCount: 1
    image:
      pullPolicy: Always
  cainjector:
    image:
      pullPolicy: Always